name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: make ciTest
      env:
        TESTCAFE_BROWSER: firefox:headless
        VUEPRESS_HOST: node
